---
- hosts: all

  vars_files:
    - default.config.yml

  roles:
    - { role: geerlingguy.dotfiles }

  tasks:
    - include_tasks: tasks/setup-ansible.yml
    - include_tasks: tasks/install-fonts.yml
    - include_tasks: tasks/install-mac-apps.yml
    - include_tasks: tasks/install-shell-apps.yml
    - include_tasks: tasks/checkout-repositories.yml
    - include_tasks: tasks/configure-tmux.yml
    - include_tasks: tasks/setup-python.yml

